import enum
from enum import Enum

class UserRole(str, Enum):
    ADMIN = "ADMIN"
    ASSET_MANAGER = "ASSET_MANAGER"
    DEPARTMENT_HEAD = "DEPARTMENT_HEAD"
    EMPLOYEE = "EMPLOYEE"

class UserStatus(str, Enum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    SUSPENDED = "SUSPENDED"

class AssetStatus(str, Enum):
    AVAILABLE = "AVAILABLE"
    ALLOCATED = "ALLOCATED"
    UNDER_MAINTENANCE = "UNDER_MAINTENANCE"
    RETIRED = "RETIRED"
    DISPOSED = "DISPOSED"
    LOST = "LOST"

class BookingStatus(str, Enum):
    UPCOMING = "UPCOMING"
    ONGOING = "ONGOING"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"

class MaintenanceStatus(str, Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    IN_PROGRESS = "IN_PROGRESS"
    RESOLVED = "RESOLVED"

class MaintenancePriority(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"

class NotificationType(str, Enum):
    ASSET_ASSIGNED = "ASSET_ASSIGNED"
    TRANSFER_REQUESTED = "TRANSFER_REQUESTED"
    TRANSFER_APPROVED = "TRANSFER_APPROVED"
    TRANSFER_REJECTED = "TRANSFER_REJECTED"
    BOOKING_CONFIRMED = "BOOKING_CONFIRMED"
    BOOKING_CANCELLED = "BOOKING_CANCELLED"
    MAINTENANCE_RAISED = "MAINTENANCE_RAISED"
    MAINTENANCE_APPROVED = "MAINTENANCE_APPROVED"
    MAINTENANCE_REJECTED = "MAINTENANCE_REJECTED"
    MAINTENANCE_RESOLVED = "MAINTENANCE_RESOLVED"
    OVERDUE_RETURN = "OVERDUE_RETURN"
    AUDIT_DISCREPANCY = "AUDIT_DISCREPANCY"
    GENERIC = "GENERIC"

class AuditCycleStatus(str, Enum):
    OPEN = "OPEN"
    CLOSED = "CLOSED"

class AuditResult(str, Enum):
    VERIFIED = "VERIFIED"
    MISSING = "MISSING"
    DAMAGED = "DAMAGED"

class AuditScopeType(str, Enum):
    DEPARTMENT = "DEPARTMENT"
    LOCATION = "LOCATION"
    ALL = "ALL"

class TransferStatus(enum.Enum):
    REQUESTED = "REQUESTED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"

class AllocationStatus(enum.Enum):
    ACTIVE = "ACTIVE"
    RETURNED = "RETURNED"
    REVOKED = "REVOKED"
