"""Update Custody models

Revision ID: 02562e2e803f
Revises: 3d085de14781
Create Date: 2026-07-12 12:16:40.161170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '02562e2e803f'
down_revision: Union[str, Sequence[str], None] = '3d085de14781'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    allocationstatus = postgresql.ENUM('ACTIVE', 'RETURNED', name='allocationstatus')
    allocationstatus.create(op.get_bind(), checkfirst=True)

    op.add_column('allocations', sa.Column('employee_id', sa.UUID(), nullable=True))
    op.add_column('allocations', sa.Column('allocated_by', sa.UUID(), nullable=False))
    op.add_column('allocations', sa.Column('expected_return', sa.DateTime(timezone=True), nullable=True))
    op.add_column('allocations', sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('allocations', sa.Column('return_condition_notes', sa.String(length=500), nullable=True))
    op.add_column('allocations', sa.Column('status', sa.Enum('ACTIVE', 'RETURNED', name='allocationstatus'), nullable=False))
    op.drop_constraint(op.f('allocations_user_id_fkey'), 'allocations', type_='foreignkey')
    op.create_foreign_key(None, 'allocations', 'users', ['employee_id'], ['id'])
    op.create_foreign_key(None, 'allocations', 'users', ['allocated_by'], ['id'])
    op.drop_column('allocations', 'actual_return_date')
    op.drop_column('allocations', 'expected_return_date')
    op.drop_column('allocations', 'user_id')
    op.add_column('transfer_requests', sa.Column('reason', sa.String(length=500), nullable=False))
    op.add_column('transfer_requests', sa.Column('requested_by', sa.UUID(), nullable=False))
    op.add_column('transfer_requests', sa.Column('decided_by', sa.UUID(), nullable=True))
    op.add_column('transfer_requests', sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('transfer_requests', sa.Column('decision_notes', sa.String(length=500), nullable=True))
    op.add_column('transfer_requests', sa.Column('allocation_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'transfer_requests', 'users', ['requested_by'], ['id'])
    op.create_foreign_key(None, 'transfer_requests', 'allocations', ['allocation_id'], ['id'])
    op.create_foreign_key(None, 'transfer_requests', 'users', ['decided_by'], ['id'])
    op.drop_column('transfer_requests', 'resolved_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfer_requests', sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transfer_requests', type_='foreignkey')
    op.drop_constraint(None, 'transfer_requests', type_='foreignkey')
    op.drop_constraint(None, 'transfer_requests', type_='foreignkey')
    op.drop_column('transfer_requests', 'allocation_id')
    op.drop_column('transfer_requests', 'decision_notes')
    op.drop_column('transfer_requests', 'decided_at')
    op.drop_column('transfer_requests', 'decided_by')
    op.drop_column('transfer_requests', 'requested_by')
    op.drop_column('transfer_requests', 'reason')
    op.add_column('allocations', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('allocations', sa.Column('expected_return_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('allocations', sa.Column('actual_return_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'allocations', type_='foreignkey')
    op.drop_constraint(None, 'allocations', type_='foreignkey')
    op.create_foreign_key(op.f('allocations_user_id_fkey'), 'allocations', 'users', ['user_id'], ['id'])
    op.drop_column('allocations', 'status')
    op.drop_column('allocations', 'return_condition_notes')
    op.drop_column('allocations', 'returned_at')
    op.drop_column('allocations', 'expected_return')
    op.drop_column('allocations', 'allocated_by')
    op.drop_column('allocations', 'employee_id')

    allocationstatus = postgresql.ENUM('ACTIVE', 'RETURNED', name='allocationstatus')
    allocationstatus.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
