"""Update Booking model

Revision ID: 2fcb0f7791b7
Revises: 02562e2e803f
Create Date: 2026-07-12 12:34:03.615940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2fcb0f7791b7'
down_revision: Union[str, Sequence[str], None] = '02562e2e803f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('start_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('bookings', sa.Column('end_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('bookings', sa.Column('purpose', sa.String(length=500), nullable=True))
    op.add_column('bookings', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('bookings', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bookings', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bookings', sa.Column('cancelled_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'bookings', 'users', ['cancelled_by'], ['id'])
    op.drop_column('bookings', 'end_time')
    op.drop_column('bookings', 'start_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('bookings', sa.Column('end_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'cancelled_by')
    op.drop_column('bookings', 'cancelled_at')
    op.drop_column('bookings', 'updated_at')
    op.drop_column('bookings', 'created_at')
    op.drop_column('bookings', 'purpose')
    op.drop_column('bookings', 'end_at')
    op.drop_column('bookings', 'start_at')
    # ### end Alembic commands ###
