"""Update Asset model

Revision ID: 3d085de14781
Revises: aa5c65fc37d8
Create Date: 2026-07-12 06:20:36.080053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d085de14781'
down_revision: Union[str, Sequence[str], None] = 'aa5c65fc37d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('tag', sa.String(length=50), nullable=False))
    op.add_column('assets', sa.Column('department_id', sa.UUID(), nullable=True))
    op.add_column('assets', sa.Column('photo_url', sa.String(length=500), nullable=True))
    op.add_column('assets', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('assets', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('assets', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('assets_asset_tag_key'), 'assets', type_='unique')
    op.create_unique_constraint(None, 'assets', ['serial_number'])
    op.create_unique_constraint(None, 'assets', ['tag'])
    op.create_foreign_key(None, 'assets', 'departments', ['department_id'], ['id'])
    op.create_foreign_key(None, 'assets', 'users', ['created_by'], ['id'])
    op.drop_column('assets', 'asset_tag')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('asset_tag', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.drop_constraint(None, 'assets', type_='unique')
    op.drop_constraint(None, 'assets', type_='unique')
    op.create_unique_constraint(op.f('assets_asset_tag_key'), 'assets', ['asset_tag'], postgresql_nulls_not_distinct=False)
    op.drop_column('assets', 'updated_at')
    op.drop_column('assets', 'created_at')
    op.drop_column('assets', 'created_by')
    op.drop_column('assets', 'photo_url')
    op.drop_column('assets', 'department_id')
    op.drop_column('assets', 'tag')
    # ### end Alembic commands ###
