"""Update Maintenance model

Revision ID: 438f684440c9
Revises: 2fcb0f7791b7
Create Date: 2026-07-12 12:49:39.368179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '438f684440c9'
down_revision: Union[str, Sequence[str], None] = '2fcb0f7791b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maintenance_requests', sa.Column('raised_by', sa.UUID(), nullable=False))
    op.add_column('maintenance_requests', sa.Column('description', sa.Text(), nullable=False))
    op.add_column('maintenance_requests', sa.Column('photo_url', sa.String(), nullable=True))
    op.add_column('maintenance_requests', sa.Column('technician_name', sa.String(), nullable=True))
    op.add_column('maintenance_requests', sa.Column('resolution_notes', sa.Text(), nullable=True))
    op.add_column('maintenance_requests', sa.Column('rejection_reason', sa.Text(), nullable=True))
    op.add_column('maintenance_requests', sa.Column('approved_by', sa.UUID(), nullable=True))
    op.add_column('maintenance_requests', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('maintenance_requests', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('maintenance_requests', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    
    # Create the Enum type first
    priority_enum = postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='maintenancepriority')
    priority_enum.create(op.get_bind())
    
    # Use postgresql USING clause to cast the existing VARCHAR column to the new Enum
    op.execute("ALTER TABLE maintenance_requests ALTER COLUMN priority TYPE maintenancepriority USING priority::maintenancepriority")
    
    op.drop_constraint('maintenance_requests_user_id_fkey', 'maintenance_requests', type_='foreignkey')
    op.create_foreign_key(None, 'maintenance_requests', 'users', ['raised_by'], ['id'])
    op.create_foreign_key(None, 'maintenance_requests', 'users', ['approved_by'], ['id'])
    op.drop_column('maintenance_requests', 'requested_at')
    op.drop_column('maintenance_requests', 'issue_description')
    op.drop_column('maintenance_requests', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maintenance_requests', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('maintenance_requests', sa.Column('issue_description', sa.VARCHAR(length=1000), autoincrement=False, nullable=False))
    op.add_column('maintenance_requests', sa.Column('requested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'maintenance_requests', type_='foreignkey')
    op.drop_constraint(None, 'maintenance_requests', type_='foreignkey')
    op.create_foreign_key(op.f('maintenance_requests_user_id_fkey'), 'maintenance_requests', 'users', ['user_id'], ['id'])
    op.alter_column('maintenance_requests', 'priority',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='maintenancepriority'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('maintenance_requests', 'updated_at')
    op.drop_column('maintenance_requests', 'created_at')
    op.drop_column('maintenance_requests', 'approved_at')
    op.drop_column('maintenance_requests', 'approved_by')
    op.drop_column('maintenance_requests', 'rejection_reason')
    op.drop_column('maintenance_requests', 'resolution_notes')
    op.drop_column('maintenance_requests', 'technician_name')
    op.drop_column('maintenance_requests', 'photo_url')
    op.drop_column('maintenance_requests', 'description')
    op.drop_column('maintenance_requests', 'raised_by')
    # ### end Alembic commands ###
