"""Update Org models

Revision ID: aa5c65fc37d8
Revises: 2155b2b8ed42
Create Date: 2026-07-12 05:53:43.345302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa5c65fc37d8'
down_revision: Union[str, Sequence[str], None] = '2155b2b8ed42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('categories', sa.Column('warranty_months', sa.Integer(), nullable=True))
    op.add_column('categories', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('categories', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('categories', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'categories', ['name'])
    op.drop_column('categories', 'warranty_period_months')
    op.add_column('departments', sa.Column('code', sa.String(length=50), nullable=True))
    op.add_column('departments', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('departments', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'departments', ['code'])
    op.create_unique_constraint(None, 'departments', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'departments', type_='unique')
    op.drop_constraint(None, 'departments', type_='unique')
    op.drop_column('departments', 'updated_at')
    op.drop_column('departments', 'created_at')
    op.drop_column('departments', 'code')
    op.add_column('categories', sa.Column('warranty_period_months', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'categories', type_='unique')
    op.drop_column('categories', 'updated_at')
    op.drop_column('categories', 'created_at')
    op.drop_column('categories', 'status')
    op.drop_column('categories', 'warranty_months')
    op.drop_column('categories', 'description')
    # ### end Alembic commands ###
